[profile.default]
src = "src"
out = "out"
libs = ["lib"]

remappings = ["@openzeppelin-upgrade/=lib/openzeppelin-contracts-upgradeable", "@openzeppelin/=lib/openzeppelin-contracts"]

# See more config options https://github.com/foundry-rs/foundry/tree/master/config